- name: Create a mountable directory if it does not exist
  file:
     path: /mnt/share
     state: directory
     owner: root
     group: root
     mode: '0777'

- name: Copy exports to /etc
  copy:
    src: exports
    dest: /etc
    mode: 0644

- name: copy export command to /etc/exports
  lineinfile:
    path: /etc/exports
    line: /mnt/share {{SUBNET_RANGE}}(rw,sync,no_subtree_check)

- name: Restart nfs-kernel-server
  service:
    name: nfs-kernel-server
    state: restarted

- name: Copy an empty mpi hosts file to /mnt/share
  copy:
    src: hosts
    dest: /mnt/share
    mode: 0777

